# Generated by Django 5.2.1 on 2025-06-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_category_name_en_category_name_ru_category_name_uz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
