# Generated by Django 4.2.23 on 2025-07-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='Key')),
                ('value', models.CharField(max_length=30, verbose_name='Value')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuratiions', to='order.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Config',
                'verbose_name_plural': 'Order Items Config',
                'unique_together': {('order_item', 'key')},
            },
        ),
    ]
